version: 0.1
phases:
  install:
    commands:
      - pip install boto3
      - aws cloudformation package --template-file sample-sam.yml --s3-bucket chapter6-lambda-function-src --output-template-file sample-sam-output.yml --no-fail-on-empty-changeset
artifacts:
  type: zip
  files:
    - sample-sam-output.yml
